### ISSUE TITLE
libhdf5.so

### ISSUE THREAD

**Issue by Sourin-chatterjee** [fbuessen/SpinParser#1]
I am facing an error message-

SpinParser | install  bin/SpinParser --debugLattice examples/square-Heisenberg.xml
bin/SpinParser: error while loading shared libraries: libhdf5.so.103: cannot open shared object file: No such file or directory

I am using Linux lite.

![issue](https://user-images.githubusercontent.com/69479701/136586687-535b4970-99bc-4156-833e-0bec1f3132c1.png)

**Comment by fbuessen** [comment]
It looks like your Linux is unable to dynamically link your HDF5 library when running the SpinParser executable. 
Usually, your Linux distribution should automatically set the correct search path to locate the library when installing the `libhdf5-dev` package, but that didn't seem to work on your system. 

There are a couple of things you can try: 
- Make sure that the HDF5 shared library actually exists on your system, i.e., try to locate the file with `locate libhdf5.so.103`
- If the file doesn't exist, you might need to install a package like `libhdf5-103`, which contains the shared HDF5 library files and should usually be automatically installed as a dependency of the `libhdf5-dev` package
- If the file exists, you can manually add it to the library search path by adding the containing directory to the environment variable `LD_LIBRARY_PATH`, e.g. `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/your/library/directory`

I hope this helps!

**Comment by Sourin-chatterjee** [comment]
Thank you, sir.
It worked.
