### ISSUE TITLE
Unable to link Mathematica

### ISSUE THREAD

**Issue by Sourin-chatterjee** [fbuessen/SpinParser#2]
I am unable to link Mathematica with Spinparser, I am facing following error.

![Issue](https://user-images.githubusercontent.com/69479701/147278839-7ab51ca2-6ac4-40a3-bb0e-11706a53775b.png)
![Python](https://user-images.githubusercontent.com/69479701/147278844-aad668db-de07-4104-9cd7-8b4b4b923298.png)

**Comment by fbuessen** [comment]
Hi, it sees that Mathematica cannot correctly locate the `spinparser.m` file, which contains the function definitions. Please make sure that the file exists in the path `opt/mathematica/spinparser.m` relative to your installation directory of SpinParser. 

Next, you should add the _absolute_ search path of the directory `opt/mathematica` to Mathematica, e.g. by invoking the command `AppendTo[$PATH, "/path/to/your/spinparser/installation/opt/mathematica"]`. Note that in the Screenshots which you shared you only added the relative path `opt/mathematica`.

**Comment by Sourin-chatterjee** [comment]
Hi,Thanks  , it worked.
