### ISSUE TITLE
Error in defining the 3 rd nn bonds  in honeycomb lattice.

### ISSUE THREAD

**Issue by QG-phy** [fbuessen/SpinParser#6]
Hi, i get an error when using SpinParser. I defined the 3 rd nn bonds  in honeycomb lattice as,

	<primitive x="3/2" y="sqrt(3)/2" z="0" />
	<primitive x="3/2" y="-sqrt(3)/2" z="0" />
	<primitive x="0" y="0" z="1" />

	<site x="0" y="0" z="0" />
	<site x="1" y="0" z="0" />

	<bond from="0" to="1" da0="0" da1="0" da2="0" />
	<bond from="1" to="0" da0="1" da1="0" da2="0" />
	<bond from="1" to="0" da0="0" da1="1" da2="0" />
	<bond from="1" to="0" da0="1" da1="1" da2="0" />
	<bond from="1" to="0" da0="1" da1="-1" da2="0" />
	<bond from="1" to="0" da0="-1" da1="1" da2="0" />

after i defined the model.xml. I  try the --debugLattice. there goes with error:

[0.580380][I] Generated exponential frequency discretization with 64 values
[0.580485][I] Generated exponential cutoff discretization with 422 values
[0.586340][I] Building lattice spin model...
[0.587404][I] 	...finding lattice parametrization
[0.587683][E] Caught exception: [InternalError]: Lattice symmetry calculation has failed. (Deviation of symmetry transformed site [n1] from target [c1] is 1.000000, should be zero)

Could you please tell me what does this error mean and is there anything wrong in my definition of  the Lattice ? 
Thank you!

**Comment by QG-phy** [comment]
Hello, i check the lattice.xml over again. i still can not figure out what is wrong there.  could you please tell me what does the error message "Lattice symmetry calculation has failed. (Deviation of symmetry transformed site [n1] from target [c1] is 1.000000, should be zero)" mean ? will appreciate it a lot.

**Comment by shishirkrpandey** [comment]
Hello,
You will have to define an additional third neighbor in your definition as follows. 
 <bond from="0" to="1" da0="-1" da1="-1" da2="0" />. 
I hope this helps.

**Comment by shishirkrpandey** [comment]
Hello, 
I do not think you need to explicitly define the third neighbor. Third neighbors are just the lattice translation of the two sites inn the unit cell and hence are well accounted for. 
What you need to do is to define your spin model with third nearest neighbor interactions where interaction parameter can be attributed to which neighbor you may want in your model. 
Dr. Buessen can correct me if I am wrong.

**Comment by fbuessen** [comment]
Hi! shishirkrpandey is right -- you shouldn't include the third-nearest neighbors in the lattice definition. 
Instead, you add them to the spin model definition. 
In the example model definition file `res/models.xml`, you can already find models on the honeycomb lattice that include nearest and second-nearest neighbor interactions. Following those examples, you can write your own extension to third-nearest neighbors. 
You can also find details about lattice and spin model definitions in Secs. 5.2 and 5.3 of the SpinParser publication arXiv:2109.13317.

**Comment by shishirkrpandey** [comment]
Hi @fbuessen , 
Kudos to you. You really have done a great job with SpinParser, particularly with the insightful documentation on arxiv. 

One related question if I may ask, in some of the references that you have cited in arxiv publication, I saw that there is a way to calculate the finite temperature properties like specific heat or susceptibility. Do you have any plans for future to extend SpinParser capabilities in that direction?

Thanks again for all the help that you provided.

**Comment by fbuessen** [comment]
The temperature dependent susceptibilities, which you can find in some publications, are obtained from a linear rescaling between the RG cutoff parameter and temperature (and therefore doesn't need to be explicitly implemented). The rescaling was first introduced in [Iqbal et al., Phys. Rev. B 94, 140408(R)]. 
You can also find some discussion of this aspect in Sec. 2.5.6 of [[F. L. Buessen, A Functional Renormalization Group Perspective on Quantum Spin Liquids in Three-Dimensional Frustrated Magnets, Ph.D. thesis, Universität zu Köln (2019)](https://kups.ub.uni-koeln.de/9986/)]
