### ISSUE TITLE
Issue while implementing fisher lattice

### ISSUE THREAD

**Issue by Sourin-chatterjee** [fbuessen/SpinParser#7]
I am trying to implement fisher lattice using Spinparser.(https://journals.aps.org/prb/abstract/10.1103/PhysRevB.102.224404)
Lattice definition that i used:
[unitcell name="fisher"]
	[primitive x="1" y="0" z="0" /]
	[primitive x="0" y="1" z="0" /]
	[primitive x="0" y="0" z="1" /]

	<site x="-1/3" y="0" z="0" />
	<site x="0" y="-1/3" z="0" />
	<site x="1/3" y="0" z="0" />
	<site x="0" y="1/3" z="0" />
	
	<bond from="0" to="1" da0="0" da1="0" da2="0" />
	<bond from="1" to="2" da0="0" da1="0" da2="0" />
	<bond from="2" to="3" da0="0" da1="0" da2="0" />
	<bond from="3" to="0" da0="0" da1="0" da2="0" />
	<bond from="2" to="0" da0="1" da1="0" da2="0" />
	<bond from="3" to="1" da0="0" da1="1" da2="0" />
[/unitcell]

The unit cell that i am taking is:
![unitcell_fisher](https://user-images.githubusercontent.com/69479701/167836246-6e54393f-38b4-48e2-b5d8-8197d45c3df8.png)

The error message is:

![error](https://user-images.githubusercontent.com/69479701/167836294-72788eb7-64cc-4201-811d-ffb3b7cbf66f.png)

**Comment by fbuessen** [comment]
Hi, Thanks for pointing this out. In principle, the Fisher lattice should work -- I'll take a look!

**Comment by fbuessen** [comment]
Hi Sourin, 
Could you provide some more information on your spin model? 
The lattice itself seems to be okay. 
I just ran a test with your lattice definition equipped with nearest neighbor Heisenberg interactions, and the lattice symmetry calculation turned out fine (model definition attached below). 
You might just have a mistake in your definition of the spin interactions. 

```xml
<unitcell name="fisher">
	<primitive x="1" y="0" z="0" />
	<primitive x="0" y="1" z="0" />
	<primitive x="0" y="0" z="1" />

	<site x="-1/3" y="0" z="0" />
	<site x="0" y="-1/3" z="0" />
	<site x="1/3" y="0" z="0" />
	<site x="0" y="1/3" z="0" />
	
	<bond from="0" to="1" da0="0" da1="0" da2="0" />
	<bond from="1" to="2" da0="0" da1="0" da2="0" />
	<bond from="2" to="3" da0="0" da1="0" da2="0" />
	<bond from="3" to="0" da0="0" da1="0" da2="0" />
	<bond from="2" to="0" da0="1" da1="0" da2="0" />
	<bond from="3" to="1" da0="0" da1="1" da2="0" />
</unitcell>
```
```xml
<model name="fisher-heisenberg">
	<!-- Heisenberg model on the Fisher lattice -->
	<interaction parameter="j" from="0,0,0,0" to="0,0,0,1" type="heisenberg" />
	<interaction parameter="j" from="0,0,0,1" to="0,0,0,2" type="heisenberg" />
	<interaction parameter="j" from="0,0,0,2" to="0,0,0,3" type="heisenberg" />
	<interaction parameter="j" from="0,0,0,3" to="0,0,0,0" type="heisenberg" />
	<interaction parameter="j" from="0,0,0,2" to="1,0,0,0" type="heisenberg" />
	<interaction parameter="j" from="0,0,0,3" to="0,1,0,1" type="heisenberg" />
</model>
```

**Comment by fbuessen** [comment]
There was a small issue in the code which could trigger the exception for lattices that contain multiple lattice bonds of different length (as is the case for your unit cell definition of the Fisher lattice). 
I just pushed a patch #8 for the issue and successfully tested your lattice definition in combination with a nearest neighbor Heisenberg model (see below for the model definition.)

```xml
<unitcell name="fisher">
	<primitive x="1" y="0" z="0" />
	<primitive x="0" y="1" z="0" />
	<primitive x="0" y="0" z="1" />

	<site x="-1/3" y="0" z="0" />
	<site x="0" y="-1/3" z="0" />
	<site x="1/3" y="0" z="0" />
	<site x="0" y="1/3" z="0" />
	
	<bond from="0" to="1" da0="0" da1="0" da2="0" />
	<bond from="1" to="2" da0="0" da1="0" da2="0" />
	<bond from="2" to="3" da0="0" da1="0" da2="0" />
	<bond from="3" to="0" da0="0" da1="0" da2="0" />
	<bond from="2" to="0" da0="1" da1="0" da2="0" />
	<bond from="3" to="1" da0="0" da1="1" da2="0" />
</unitcell>
```

```xml
<model name="fisher-heisenberg">
	<!-- Heisenberg model on the Fisher lattice -->
	<interaction parameter="j" from="0,0,0,0" to="0,0,0,1" type="heisenberg" />
	<interaction parameter="j" from="0,0,0,1" to="0,0,0,2" type="heisenberg" />
	<interaction parameter="j" from="0,0,0,2" to="0,0,0,3" type="heisenberg" />
	<interaction parameter="j" from="0,0,0,3" to="0,0,0,0" type="heisenberg" />
	<interaction parameter="j" from="0,0,0,2" to="1,0,0,0" type="heisenberg" />
	<interaction parameter="j" from="0,0,0,3" to="0,1,0,1" type="heisenberg" />
</model>
```

**Comment by Sourin-chatterjee** [comment]
Thanks, Finn. It's working fine now .
